CREATE TABLE patient (
    id CHARACTER VARYING (255) PRIMARY KEY,
    identifier CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE doctor (
    id CHARACTER VARYING (255) PRIMARY KEY,
    identifier CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE organization (
    id CHARACTER VARYING (255) PRIMARY KEY,
    identifier CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL
);
