version: '2'
services:
  discoveryserver:
    image: hunters/discovery-server:first
    ports:
      - "8761:8761"
  configserver:
    image: hunters/config-server:first
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://discoveryserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "IMSYMMETRIC"
  database:
    image: hunters/database:first
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres_local"
      POSTGRES_PASSWORD: "p0stgr@s_local"
      POSTGRES_DB: "local"
  patientservice:
    image: hunters/patient-service:first
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      EUREKASERVER_URI: "http://discoveryserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  organizationservice:
    image: hunters/organization-service:first
    ports:
      - "8081:8081"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      EUREKASERVER_URI: "http://discoveryserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  doctorservice:
    image: hunters/doctor-service:first
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      EUREKASERVER_URI: "http://discoveryserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
