example:
  property: "I AM A PROD PROPERTY OVERRIDE"
spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://database:5432/prod"
    username: "postgres_prod"
    password: "p0stgr@s_prod"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis:
  server: "redis"
  port: "6379"
signing:
  key: "345345fsdfsf5345"